//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public int ID { get; set; }
        public int PlaceID { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public int NeedMinLevel { get; set; }
        public int NeedMaxLevel { get; set; }
        public string PreAchievementID { get; set; }
        public int IsOther { get; set; }
        public int AchievementType { get; set; }
        public bool CanHide { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int AchievementPoint { get; set; }
    }
}
