//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement_Reward
    {
        public int AchievementID { get; set; }
        public int RewardType { get; set; }
        public string RewardPara { get; set; }
        public int RewardValueId { get; set; }
        public int RewardCount { get; set; }
    }
}
