//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active_Condition
    {
        public int ID { get; set; }
        public int ActiveID { get; set; }
        public int Conditiontype { get; set; }
        public int Condition { get; set; }
        public string LimitGrade { get; set; }
        public string AwardId { get; set; }
        public bool IsMult { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
