//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active_Award
    {
        public int ActiveID { get; set; }
        public int ItemID { get; set; }
        public int Count { get; set; }
        public int ValidDate { get; set; }
        public int StrengthenLevel { get; set; }
        public int AttackCompose { get; set; }
        public int DefendCompose { get; set; }
        public int LuckCompose { get; set; }
        public int AgilityCompose { get; set; }
        public int Gold { get; set; }
        public int Money { get; set; }
        public int Sex { get; set; }
        public int Mark { get; set; }
        public int id { get; set; }
    }
}
