//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public int AuctionID { get; set; }
        public string Name { get; set; }
        public int Category { get; set; }
        public int AuctioneerID { get; set; }
        public string AuctioneerName { get; set; }
        public int ItemID { get; set; }
        public int PayType { get; set; }
        public int Price { get; set; }
        public int Rise { get; set; }
        public int Mouthful { get; set; }
        public System.DateTime BeginDate { get; set; }
        public int ValidDate { get; set; }
        public int BuyerID { get; set; }
        public string BuyerName { get; set; }
        public bool IsExist { get; set; }
        public int TemplateID { get; set; }
        public int Random { get; set; }
    }
}
