//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ball
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public double Power { get; set; }
        public int Radii { get; set; }
        public string FlyingPartical { get; set; }
        public string BombPartical { get; set; }
        public bool IsSpin { get; set; }
        public int Mass { get; set; }
        public double SpinVA { get; set; }
        public int SpinV { get; set; }
        public int Amount { get; set; }
        public int Wind { get; set; }
        public int DragIndex { get; set; }
        public int Weight { get; set; }
        public bool Shake { get; set; }
        public string ShootSound { get; set; }
        public string BombSound { get; set; }
        public int Delay { get; set; }
        public int ActionType { get; set; }
        public bool HasTunnel { get; set; }
    }
}
