//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consortia_Apply_Ally
    {
        public int ID { get; set; }
        public int Consortia1ID { get; set; }
        public int Consortia2ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Remark { get; set; }
        public bool IsExist { get; set; }
        public int State { get; set; }
    }
}
