//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consortia_Users
    {
        public int ID { get; set; }
        public int ConsortiaID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> RatifierID { get; set; }
        public string RatifierName { get; set; }
        public int DutyID { get; set; }
        public string Remark { get; set; }
        public bool IsBanChat { get; set; }
        public bool IsExist { get; set; }
    }
}
