//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consortia_Level
    {
        public int Level { get; set; }
        public int Riches { get; set; }
        public int Deduct { get; set; }
        public int NeedGold { get; set; }
        public int NeedItem { get; set; }
        public int Reward { get; set; }
        public int Count { get; set; }
        public int StoreRiches { get; set; }
        public int SmithRiches { get; set; }
        public int ShopRiches { get; set; }
        public int KickMax { get; set; }
    }
}
