//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consortia
    {
        public int ConsortiaID { get; set; }
        public string ConsortiaName { get; set; }
        public int Honor { get; set; }
        public int CreatorID { get; set; }
        public string CreatorName { get; set; }
        public int ChairmanID { get; set; }
        public string ChairmanName { get; set; }
        public string Description { get; set; }
        public string Placard { get; set; }
        public int Level { get; set; }
        public int MaxCount { get; set; }
        public int CelebCount { get; set; }
        public System.DateTime BuildDate { get; set; }
        public int Repute { get; set; }
        public int Count { get; set; }
        public string IP { get; set; }
        public int Port { get; set; }
        public bool IsExist { get; set; }
        public int Riches { get; set; }
        public System.DateTime DeductDate { get; set; }
        public System.DateTime WarnDate { get; set; }
        public int LastDayRiches { get; set; }
        public int AddDayRiches { get; set; }
        public int LastWeekRiches { get; set; }
        public int AddWeekRiches { get; set; }
        public int LastDayHonor { get; set; }
        public int AddDayHonor { get; set; }
        public int LastWeekHonor { get; set; }
        public int AddWeekHonor { get; set; }
        public bool OpenApply { get; set; }
        public int StoreLevel { get; set; }
        public int SmithLevel { get; set; }
        public int ShopLevel { get; set; }
        public bool Rename { get; set; }
        public System.DateTime KickDate { get; set; }
        public int KickCount { get; set; }
        public int FightPower { get; set; }
        public bool IsSystemCreate { get; set; }
        public bool IsActive { get; set; }
    }
}
