//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_Award
    {
        public int ID { get; set; }
        public int Type { get; set; }
        public int TemplateID { get; set; }
        public int Count { get; set; }
        public int ValidDate { get; set; }
        public bool IsBinds { get; set; }
        public int Sex { get; set; }
        public string Remark { get; set; }
        public string CountRemark { get; set; }
        public int GetWay { get; set; }
    }
}
