//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
        public Entities(string conn) : base(conn)
        {
        }
    

    
        public virtual DbSet<Achievement> Achievement { get; set; }
        public virtual DbSet<Achievement_Condition> Achievement_Condition { get; set; }
        public virtual DbSet<Achievement_Data> Achievement_Data { get; set; }
        public virtual DbSet<Achievement_Reward> Achievement_Reward { get; set; }
        public virtual DbSet<Active> Active { get; set; }
        public virtual DbSet<Active_Condition> Active_Condition { get; set; }
        public virtual DbSet<Active_Number> Active_Number { get; set; }
        public virtual DbSet<Auction> Auction { get; set; }
        public virtual DbSet<Bag_Init> Bag_Init { get; set; }
        public virtual DbSet<Ball> Ball { get; set; }
        public virtual DbSet<Consortia> Consortia { get; set; }
        public virtual DbSet<Consortia_Ally> Consortia_Ally { get; set; }
        public virtual DbSet<Consortia_Apply_Ally> Consortia_Apply_Ally { get; set; }
        public virtual DbSet<Consortia_Apply_Users> Consortia_Apply_Users { get; set; }
        public virtual DbSet<Consortia_Duty> Consortia_Duty { get; set; }
        public virtual DbSet<Consortia_Equip_Control> Consortia_Equip_Control { get; set; }
        public virtual DbSet<Consortia_Event> Consortia_Event { get; set; }
        public virtual DbSet<Consortia_Invite_Users> Consortia_Invite_Users { get; set; }
        public virtual DbSet<Consortia_Level> Consortia_Level { get; set; }
        public virtual DbSet<Consortia_Users> Consortia_Users { get; set; }
        public virtual DbSet<Daily_Award> Daily_Award { get; set; }
        public virtual DbSet<Drop_Condiction> Drop_Condiction { get; set; }
        public virtual DbSet<Drop_Item> Drop_Item { get; set; }
        public virtual DbSet<Fight_Rate> Fight_Rate { get; set; }
        public virtual DbSet<Fusion> Fusion { get; set; }
        public virtual DbSet<Game_Map> Game_Map { get; set; }
        public virtual DbSet<Item_Fusion> Item_Fusion { get; set; }
        public virtual DbSet<Item_Record_Type> Item_Record_Type { get; set; }
        public virtual DbSet<Item_Strengthen> Item_Strengthen { get; set; }
        public virtual DbSet<Item_Strengthen_Goods> Item_Strengthen_Goods { get; set; }
        public virtual DbSet<Map_Week> Map_Week { get; set; }
        public virtual DbSet<Marry_Apply> Marry_Apply { get; set; }
        public virtual DbSet<Marry_Info> Marry_Info { get; set; }
        public virtual DbSet<Marry_Room_Info> Marry_Room_Info { get; set; }
        public virtual DbSet<Mission_Info> Mission_Info { get; set; }
        public virtual DbSet<NPC_Info> NPC_Info { get; set; }
        public virtual DbSet<Pve_Info> Pve_Info { get; set; }
        public virtual DbSet<Quest_Condiction> Quest_Condiction { get; set; }
        public virtual DbSet<QuestData> QuestData { get; set; }
        public virtual DbSet<Rename_Consortia> Rename_Consortia { get; set; }
        public virtual DbSet<Rename_Nick> Rename_Nick { get; set; }
        public virtual DbSet<Server_List> Server_List { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<Shop_Goods> Shop_Goods { get; set; }
        public virtual DbSet<Shop_Goods_Box> Shop_Goods_Box { get; set; }
        public virtual DbSet<Shop_Goods_Categorys> Shop_Goods_Categorys { get; set; }
        public virtual DbSet<Spa_Room_Info> Spa_Room_Info { get; set; }
        public virtual DbSet<Sys_Users_Buff> Sys_Users_Buff { get; set; }
        public virtual DbSet<Sys_Users_Charge> Sys_Users_Charge { get; set; }
        public virtual DbSet<Sys_Users_Detail> Sys_Users_Detail { get; set; }
        public virtual DbSet<Sys_Users_Fight> Sys_Users_Fight { get; set; }
        public virtual DbSet<Sys_Users_Friends> Sys_Users_Friends { get; set; }
        public virtual DbSet<Sys_Users_Goods> Sys_Users_Goods { get; set; }
        public virtual DbSet<Sys_Users_Info> Sys_Users_Info { get; set; }
        public virtual DbSet<Sys_Users_Messages> Sys_Users_Messages { get; set; }
        public virtual DbSet<Sys_Users_Order> Sys_Users_Order { get; set; }
        public virtual DbSet<Sys_Users_Password> Sys_Users_Password { get; set; }
        public virtual DbSet<Sys_Users_Record> Sys_Users_Record { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Active_Award> Active_Award { get; set; }
        public virtual DbSet<Map_Server> Map_Server { get; set; }
        public virtual DbSet<Quest> Quest { get; set; }
        public virtual DbSet<Quest_Goods> Quest_Goods { get; set; }
        public virtual DbSet<Rate> Rate { get; set; }
        public virtual DbSet<User_Get_Box> User_Get_Box { get; set; }
    }
}
