//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drop_Item
    {
        public int Id { get; set; }
        public int DropId { get; set; }
        public int ItemId { get; set; }
        public int ValueDate { get; set; }
        public bool IsBind { get; set; }
        public int Random { get; set; }
        public int BeginData { get; set; }
        public int EndData { get; set; }
        public bool IsTips { get; set; }
        public bool IsLogs { get; set; }
    }
}
