//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fight_Rate
    {
        public int ID { get; set; }
        public int ServerID { get; set; }
        public int Rate { get; set; }
        public System.DateTime BeginDay { get; set; }
        public System.DateTime EndDay { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int BoyTemplateID { get; set; }
        public int GirlTemplateID { get; set; }
        public string SelfCue { get; set; }
        public string EnemyCue { get; set; }
        public string Name { get; set; }
    }
}
