//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fusion
    {
        public int FusionID { get; set; }
        public int Item1 { get; set; }
        public int Item2 { get; set; }
        public int Item3 { get; set; }
        public int Item4 { get; set; }
        public int Item5 { get; set; }
        public int Item6 { get; set; }
        public int Item7 { get; set; }
        public int Item8 { get; set; }
        public int Item9 { get; set; }
        public int Item10 { get; set; }
        public int Reward1 { get; set; }
        public int Random1 { get; set; }
        public int Reward2 { get; set; }
        public int Random2 { get; set; }
        public int Reward3 { get; set; }
        public int Random3 { get; set; }
        public int Leave { get; set; }
    }
}
