//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Map
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ForegroundWidth { get; set; }
        public int ForegroundHeight { get; set; }
        public int BackroundWidht { get; set; }
        public int BackroundHeight { get; set; }
        public int DeadWidth { get; set; }
        public int DeadHeight { get; set; }
        public int Weight { get; set; }
        public int DragIndex { get; set; }
        public string ForePic { get; set; }
        public string BackPic { get; set; }
        public string DeadPic { get; set; }
        public string Pic { get; set; }
        public string Remark { get; set; }
        public string BackMusic { get; set; }
        public string PosX { get; set; }
        public int Type { get; set; }
        public string PosX1 { get; set; }
        public string PosX2 { get; set; }
    }
}
