//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Strengthen_Goods
    {
        public int ID { get; set; }
        public int Level { get; set; }
        public int CurrentEquip { get; set; }
        public int GainEquip { get; set; }
        public int OrginEquip { get; set; }
    }
}
