//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marry_Apply
    {
        public int UserID { get; set; }
        public int ApplyUserID { get; set; }
        public string ApplyUserName { get; set; }
        public int ApplyType { get; set; }
        public string LoveProclamation { get; set; }
        public Nullable<bool> ApplyResult { get; set; }
        public bool isExist { get; set; }
        public bool isDeal { get; set; }
        public int ID { get; set; }
        public System.DateTime ApplyDate { get; set; }
    }
}
