//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marry_Room_Info
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public int GroomID { get; set; }
        public string GroomName { get; set; }
        public int BrideID { get; set; }
        public string BrideName { get; set; }
        public string Pwd { get; set; }
        public int AvailTime { get; set; }
        public int MaxCount { get; set; }
        public bool GuestInvite { get; set; }
        public int MapIndex { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime BreakTime { get; set; }
        public string RoomIntroduction { get; set; }
        public int ServerID { get; set; }
        public bool IsHymeneal { get; set; }
        public bool isExist { get; set; }
        public bool IsGunsaluteUsed { get; set; }
    }
}
