//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission_Info
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TotalCount { get; set; }
        public int TotalTurn { get; set; }
        public string Script { get; set; }
        public string Success { get; set; }
        public string Failure { get; set; }
        public string Description { get; set; }
        public Nullable<int> IncrementDelay { get; set; }
        public Nullable<int> Delay { get; set; }
        public string Title { get; set; }
        public Nullable<int> Param1 { get; set; }
        public Nullable<int> Param2 { get; set; }
        public int TakeCard { get; set; }
    }
}
