//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPC_Info
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        public int Camp { get; set; }
        public int Type { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public int Blood { get; set; }
        public Nullable<int> MoveMin { get; set; }
        public Nullable<int> MoveMax { get; set; }
        public Nullable<int> BaseDamage { get; set; }
        public Nullable<int> BaseGuard { get; set; }
        public Nullable<int> Defence { get; set; }
        public Nullable<int> Agility { get; set; }
        public Nullable<int> Lucky { get; set; }
        public Nullable<int> Attack { get; set; }
        public string ModelID { get; set; }
        public string ResourcesPath { get; set; }
        public string DropRate { get; set; }
        public int Experience { get; set; }
        public int Delay { get; set; }
        public int Immunity { get; set; }
        public Nullable<int> Alert { get; set; }
        public Nullable<int> Range { get; set; }
        public Nullable<int> Preserve { get; set; }
        public string Script { get; set; }
        public int FireX { get; set; }
        public int FireY { get; set; }
        public int DropId { get; set; }
        public int MaxBeatDis { get; set; }
    }
}
