//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pve_Info
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> LevelLimits { get; set; }
        public string SimpleTemplateIds { get; set; }
        public string NormalTemplateIds { get; set; }
        public string HardTemplateIds { get; set; }
        public string TerrorTemplateIds { get; set; }
        public string Pic { get; set; }
        public string Description { get; set; }
        public string SimpleGameScript { get; set; }
        public string NormalGameScript { get; set; }
        public string HardGameScript { get; set; }
        public string TerrorGameScript { get; set; }
        public int Ordering { get; set; }
        public string AdviceTips { get; set; }
    }
}
