//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rename_Consortia
    {
        public int ID { get; set; }
        public int ConsortiaID { get; set; }
        public string ConsortiaName { get; set; }
        public string NickName { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsExist { get; set; }
    }
}
