//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server_List
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public Nullable<int> Port { get; set; }
        public int State { get; set; }
        public int Online { get; set; }
        public int Total { get; set; }
        public int Room { get; set; }
        public string Remark { get; set; }
        public string RSA { get; set; }
        public int MustLevel { get; set; }
        public int LowestLevel { get; set; }
        public bool NewerServer { get; set; }
    }
}
