//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ID { get; set; }
        public int ShopID { get; set; }
        public int GroupID { get; set; }
        public int TemplateID { get; set; }
        public int BuyType { get; set; }
        public int Sort { get; set; }
        public int IsBind { get; set; }
        public int IsVouch { get; set; }
        public int Label { get; set; }
        public decimal Beat { get; set; }
        public int AUnit { get; set; }
        public int APrice1 { get; set; }
        public int AValue1 { get; set; }
        public int APrice2 { get; set; }
        public int AValue2 { get; set; }
        public int APrice3 { get; set; }
        public int AValue3 { get; set; }
        public int BUnit { get; set; }
        public int BPrice1 { get; set; }
        public int BValue1 { get; set; }
        public int BPrice2 { get; set; }
        public int BValue2 { get; set; }
        public int BPrice3 { get; set; }
        public int BValue3 { get; set; }
        public int CUnit { get; set; }
        public int CPrice1 { get; set; }
        public int CValue1 { get; set; }
        public int CPrice2 { get; set; }
        public int CValue2 { get; set; }
        public int CPrice3 { get; set; }
        public int CValue3 { get; set; }
        public int LimitCount { get; set; }
        public bool IsCheap { get; set; }
    }
}
