//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Goods_Box
    {
        public int Id { get; set; }
        public int DataId { get; set; }
        public int TemplateId { get; set; }
        public bool IsSelect { get; set; }
        public bool IsBind { get; set; }
        public int ItemValid { get; set; }
        public int ItemCount { get; set; }
        public int StrengthenLevel { get; set; }
        public int AttackCompose { get; set; }
        public int DefendCompose { get; set; }
        public int AgilityCompose { get; set; }
        public int LuckCompose { get; set; }
        public int Random { get; set; }
        public bool IsTips { get; set; }
        public bool IsLogs { get; set; }
    }
}
