//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Goods
    {
        public int TemplateID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
        public int Attack { get; set; }
        public int Defence { get; set; }
        public int Agility { get; set; }
        public int Luck { get; set; }
        public int Level { get; set; }
        public int Quality { get; set; }
        public string Pic { get; set; }
        public int MaxCount { get; set; }
        public int NeedSex { get; set; }
        public int NeedLevel { get; set; }
        public bool CanStrengthen { get; set; }
        public bool CanCompose { get; set; }
        public bool CanDrop { get; set; }
        public bool CanEquip { get; set; }
        public bool CanUse { get; set; }
        public bool CanDelete { get; set; }
        public string Script { get; set; }
        public string Data { get; set; }
        public string Colors { get; set; }
        public int Property1 { get; set; }
        public int Property2 { get; set; }
        public int Property3 { get; set; }
        public int Property4 { get; set; }
        public int Property5 { get; set; }
        public int Property6 { get; set; }
        public int Property7 { get; set; }
        public int Property8 { get; set; }
        public int Valid { get; set; }
        public int Count { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public int BindType { get; set; }
        public int FusionType { get; set; }
        public int FusionRate { get; set; }
        public int FusionNeedRate { get; set; }
        public string Hole { get; set; }
        public int RefineryLevel { get; set; }
        public string ReclaimValue { get; set; }
        public int ReclaimType { get; set; }
        public bool Present { get; set; }
        public bool IsOnly { get; set; }
    }
}
