//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spa_Room_Info
    {
        public int RoomID { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string Pwd { get; set; }
        public int AvailTime { get; set; }
        public int MaxCount { get; set; }
        public int MapIndex { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime BreakTime { get; set; }
        public string RoomIntroduction { get; set; }
        public bool isExist { get; set; }
        public int RoomType { get; set; }
        public int ServerID { get; set; }
        public int RoomNumber { get; set; }
    }
}
