//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users_Order
    {
        public int UserID { get; set; }
        public int Repute { get; set; }
        public int ReputeOffer { get; set; }
        public int BoxProgression { get; set; }
        public int GetBoxLevel { get; set; }
        public System.DateTime AddGPLastDate { get; set; }
        public System.DateTime BoxGetDate { get; set; }
        public int AlreadyGetBox { get; set; }
    }
}
