//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users_Fight
    {
        public int UserID { get; set; }
        public int Attack { get; set; }
        public int Defence { get; set; }
        public int Luck { get; set; }
        public int Agility { get; set; }
        public int Delay { get; set; }
        public string Honor { get; set; }
        public string Map { get; set; }
        public string Directory { get; set; }
        public bool IsExist { get; set; }
    }
}
