//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users_Password
    {
        public int UserID { get; set; }
        public string PasswordQuestion1 { get; set; }
        public string PasswordAnswer1 { get; set; }
        public string PasswordQuestion2 { get; set; }
        public string PasswordAnswer2 { get; set; }
        public Nullable<System.DateTime> LastFindDate { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
    }
}
