//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users_Messages
    {
        public int ID { get; set; }
        public int SenderID { get; set; }
        public string Sender { get; set; }
        public int ReceiverID { get; set; }
        public string Receiver { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime SendTime { get; set; }
        public bool IsRead { get; set; }
        public bool IsDelR { get; set; }
        public bool IfDelS { get; set; }
        public bool IsDelete { get; set; }
        public string Annex1 { get; set; }
        public string Annex2 { get; set; }
        public int Gold { get; set; }
        public int Money { get; set; }
        public bool IsExist { get; set; }
        public int Type { get; set; }
        public string Remark { get; set; }
        public int ValidDate { get; set; }
        public string Annex1Name { get; set; }
        public string Annex2Name { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Annex3 { get; set; }
        public string Annex4 { get; set; }
        public string Annex5 { get; set; }
        public string Annex3Name { get; set; }
        public string Annex4Name { get; set; }
        public string Annex5Name { get; set; }
        public string AnnexRemark { get; set; }
        public int GiftToken { get; set; }
    }
}
