//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users_Detail
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsConsortia { get; set; }
        public int ConsortiaID { get; set; }
        public bool Sex { get; set; }
        public int Win { get; set; }
        public int Total { get; set; }
        public int Escape { get; set; }
        public int GP { get; set; }
        public string Honor { get; set; }
        public int Gold { get; set; }
        public int Money { get; set; }
        public string Style { get; set; }
        public string Colors { get; set; }
        public int Hide { get; set; }
        public int Grade { get; set; }
        public int State { get; set; }
        public int IsFirst { get; set; }
        public int Repute { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public Nullable<System.DateTime> ExpendDate { get; set; }
        public string ActiveIP { get; set; }
        public System.DateTime ForbidDate { get; set; }
        public int Offer { get; set; }
        public string Skin { get; set; }
        public bool IsExist { get; set; }
        public int ReputeOffer { get; set; }
        public Nullable<System.DateTime> LastDateSecond { get; set; }
        public Nullable<System.DateTime> LastDateThird { get; set; }
        public int LoginCount { get; set; }
        public int OnlineTime { get; set; }
        public int AntiAddiction { get; set; }
        public Nullable<System.DateTime> AntiDate { get; set; }
        public int RichesOffer { get; set; }
        public int RichesRob { get; set; }
        public int LastDayGP { get; set; }
        public int AddDayGP { get; set; }
        public int LastWeekGP { get; set; }
        public int AddWeekGP { get; set; }
        public int LastDayOffer { get; set; }
        public int AddDayOffer { get; set; }
        public int LastWeekOffer { get; set; }
        public int AddWeekOffer { get; set; }
        public int CheckCount { get; set; }
        public string Site { get; set; }
        public bool IsMarried { get; set; }
        public int SpouseID { get; set; }
        public string SpouseName { get; set; }
        public int MarryInfoID { get; set; }
        public int DayLoginCount { get; set; }
        public string ForbidReason { get; set; }
        public bool IsCreatedMarryRoom { get; set; }
        public string PasswordTwo { get; set; }
        public int SelfMarryRoomID { get; set; }
        public bool IsGotRing { get; set; }
        public string ServerName { get; set; }
        public bool Rename { get; set; }
        public int Nimbus { get; set; }
        public System.DateTime LastAward { get; set; }
        public int GiftToken { get; set; }
        public byte[] QuestSite { get; set; }
        public string PvePermission { get; set; }
        public int FightPower { get; set; }
        public int AnswerSite { get; set; }
        public System.DateTime LastAuncherAward { get; set; }
        public int ChatCount { get; set; }
        public string FightLabPermission { get; set; }
        public int SpaPubGoldRoomLimit { get; set; }
        public int OnlineTimeSecond { get; set; }
        public int OnlineTimeThird { get; set; }
        public System.DateTime LastSpaDate { get; set; }
        public int AchievementPoint { get; set; }
        public string Rank { get; set; }
        public int SpaPubMoneyRoomLimit { get; set; }
        public bool IsInSpaPubGoldToday { get; set; }
        public bool IsInSpaPubMoneyToday { get; set; }
        public int ChargedMoney { get; set; }
        public int VIPLevel { get; set; }
        public int VIPGiftLevel { get; set; }
    }
}
