//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users_Goods
    {
        public int ItemID { get; set; }
        public int UserID { get; set; }
        public int BagType { get; set; }
        public int TemplateID { get; set; }
        public int Place { get; set; }
        public int Count { get; set; }
        public bool IsJudge { get; set; }
        public string Color { get; set; }
        public bool IsExist { get; set; }
        public int StrengthenLevel { get; set; }
        public int AttackCompose { get; set; }
        public int DefendCompose { get; set; }
        public int LuckCompose { get; set; }
        public int AgilityCompose { get; set; }
        public string Skin { get; set; }
        public bool IsBinds { get; set; }
        public bool IsUsed { get; set; }
        public System.DateTime BeginDate { get; set; }
        public int ValidDate { get; set; }
        public System.DateTime RemoveDate { get; set; }
        public int RemoveType { get; set; }
        public int Hole1 { get; set; }
        public int Hole2 { get; set; }
        public int Hole3 { get; set; }
        public int Hole4 { get; set; }
        public int Hole5 { get; set; }
        public int Hole6 { get; set; }
        public int StrengthenRefineryLevel { get; set; }
    }
}
