using System;
namespace Game.Logic.LogEnum
{
	public enum LogMoneyType
	{
		Auction = 1,
		Mail,
		Shop,
		Marry,
		Consortia,
		Item,
		Charge,
		Award,
		Box,
		Game,
		Spa,
		Auction_Update = 101,
		Mail_Money = 201,
		Mail_Pay,
		Mail_Send,
		Shop_Buy = 301,
		Shop_Continue,
		Shop_Card,
		Shop_Present,
		Shop_BuySale,
		MoneyToGold,
		Marry_Spark = 401,
		Marry_Stage,
		Marry_Gift,
		Marry_Follow,
		Marry_Unmarry,
		Marry_Room,
		Marry_RoomAdd,
		Marry_Flower,
		Marry_Hymeneal = 410,
		Consortia_Rich = 412,
		Item_Move = 601,
		Item_Color,
		DismountGem,
		Charge_RMB = 701,
		Award_Daily = 801,
		Award_Quest,
		Award_Drop,
		Award_Answer,
		Award_BossDrop,
		Award_TakeCard,
		Box_Open = 901,
		Game_Boos = 1001,
		Game_PaymentTakeCard,
		Game_TryAgain,
		Game_Other,
		Game_Shoot,
		Game_Dispatches,
		Spa_Room_Creat = 1106,
		Spa_Room_Login = 1104,
		Spa_Room_Continue = 1102
	}
}
