/*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.    
*/


namespace NVelocity.Runtime.Parser
{
    /* Generated By:JJTree: Do not edit this line. ParserTreeConstants.java */

    public class ParserTreeConstants
    {
        public const int JJTPROCESS = 0;
        public const int JJTVOID = 1;
        public const int JJTESCAPEDDIRECTIVE = 2;
        public const int JJTESCAPE = 3;
        public const int JJTCOMMENT = 4;
        public const int JJTFLOATINGPOINTLITERAL = 5;
        public const int JJTINTEGERLITERAL = 6;
        public const int JJTSTRINGLITERAL = 7;
        public const int JJTIDENTIFIER = 8;
        public const int JJTWORD = 9;
        public const int JJTDIRECTIVE = 10;
        public const int JJTBLOCK = 11;
        public const int JJTMAP = 12;
        public const int JJTOBJECTARRAY = 13;
        public const int JJTINTEGERRANGE = 14;
        public const int JJTMETHOD = 15;
        public const int JJTREFERENCE = 16;
        public const int JJTTRUE = 17;
        public const int JJTFALSE = 18;
        public const int JJTTEXT = 19;
        public const int JJTIFSTATEMENT = 20;
        public const int JJTELSESTATEMENT = 21;
        public const int JJTELSEIFSTATEMENT = 22;
        public const int JJTSETDIRECTIVE = 23;
        public const int JJTSTOP = 24;
        public const int JJTEXPRESSION = 25;
        public const int JJTASSIGNMENT = 26;
        public const int JJTORNODE = 27;
        public const int JJTANDNODE = 28;
        public const int JJTEQNODE = 29;
        public const int JJTNENODE = 30;
        public const int JJTLTNODE = 31;
        public const int JJTGTNODE = 32;
        public const int JJTLENODE = 33;
        public const int JJTGENODE = 34;
        public const int JJTADDNODE = 35;
        public const int JJTSUBTRACTNODE = 36;
        public const int JJTMULNODE = 37;
        public const int JJTDIVNODE = 38;
        public const int JJTMODNODE = 39;
        public const int JJTNOTNODE = 40;
        public static readonly string[] jjtNodeName = new string[] { "process", "void", "EscapedDirective", "Escape", "Comment", "FloatingPointLiteral", "IntegerLiteral", "StringLiteral", "Identifier", "Word", "Directive", "Block", "Map", "ObjectArray", "IntegerRange", "Method", "Reference", "True", "False", "Text", "IfStatement", "ElseStatement", "ElseIfStatement", "SetDirective", "Stop", "Expression", "Assignment", "OrNode", "AndNode", "EQNode", "NENode", "LTNode", "GTNode", "LENode", "GENode", "AddNode", "SubtractNode", "MulNode", "DivNode", "ModNode", "NotNode" };
    }
}