using System;
namespace Game.Server.Packets
{
	public enum ePackageType : byte
	{
		SERVER_READY,
		LOGIN,
		KIT_USER,
		SYS_MESS,
		PING,
		SYS_DATE,
		NETWORK,
		RSAKEY,
		CLIENT_LOG,
		CHARGE_MONEY,
		SYS_NOTICE,
		ACTIVE_PULLDOWN,
		EDITION_ERROR,
		DAILY_AWARD,
		GET_ITEM_MESS,
		USER_ANSWER,
		SCENE_LOGIN,
		SCENE_READY,
		SCENE_ADD_USER,
		SCENE_CHAT,
		SCENE_SMILE,
		SCENE_REMOVE_USER,
		SCENE_GAME_START,
		SCENE_GAME_STOP,
		SCENE_CHANNEL_CHANGE,
        //AREA_BIG_BUGLE,重复
        PASSWORD_TWO,
        VIP_UPDATE, //ADD BY LSJ
        WORLDBOSS_JOIN,//ADD BY LSJ

        //27

        CHANGE_STATE = 32,
		CHANGE_NICKNAME,
        //33

		AC_ACTION = 35,
		SYNCH_ACTION,
		CHAT_PERSONAL,
		UPDATE_PRIVATE_INFO,
        //38

		SAVE_STYLE = 41,
		DELETE_ITEM,
		CONSORTIA_MAIL_MESSAGE,
		BUY_ITEM,

        //44

		BUY_SALEITEM = 46,
		UNCHAIN_ITEM,
		SEll_ITEM,
		CHANGE_PLACE_ITEM,
		FIGHT_NPC,
		UPDATE_ITEM,
		CHAIN_ITEM,
		GET_BOX,
		PROP_BUY,
		PROP_SELL,
		PROP_CHAIN,
		GOODS_PRESENT,
		ITEM_COMPOSE,
		ITEM_STRENGTHEN,
		ITEM_HIDE,
		ITEM_TRANSFER,
		ITEM_CONTINUE,
		ITEM_OPENUP,
		GRID_GOODS,
		GRID_PROP,
		EQUIP_CHANGE,
		UPDATE_PlAYER_INFO,
        //67

		SCENE_USERS_LIST = 69,
		GAME_INVITE,
		S_BUGLE,
		B_BUGLE,
		A_BIG_BUGLE,
		ITEM_EQUIP,
		PROP_DELETE,
		ITEM_FUSION_PREVIEW,
        ITEM_OVERDUE,
        ITEM_FUSION,
		ITEM_STORE,
        CHAT_GROUP,
        GAME_ROOM_LOGIN,
        GAME_PLAYER_ENTER,
        GAME_PLAYER_EXIT,
        //83

        GAME_START = 86,
        PLAYER_STATE,
        INSUFFICIENT_MONEY,
        //88

        GAME_VISITOR_DATA = 93,
        GAME_ROOM_CREATE,
        GAME_ROOMLIST_UPDATE,
        GAME_ROOM_CLEAR,
        GAME_ROOM_HOST,
        GAME_ROOM_KICK,
        //98

        GAME_ROOM_UPDATE_PLACE = 100,
        
        GAME_TEAM = 102,

        GAME_CHANGE_MAP = 104,
        GAME_TEAM_TYPE,
        //105

        GAME_ROOM_SETUP_CHANGE = 107,
        GAME_TAKE_TEMP,
        UPDATE_ROOM_LIST,
        ITEM_REFINERY,
		ITEM_REFINERY_PREVIEW,
        DELETE_MAIL,
        GET_MAIL_ATTACHMENT,
        UPDATE_MAIL,
        UPDATE_NEW_MAIL,
        SEND_MAIL,
        MAIL_RESPONSE,
        MAIL_CANCEL,
        LINKREQUEST_GOODS,
		ITEM_TREND,
		ITEM_INLAY,
		CLEAR_HIDE_BAG,
		DISPATCHES,
        ARRANGE_BAG,
        DISMOUNT_GEM,
        EXCHANGE_MONEY_TO_GOLD,
        REClAIM_ITEM = 127,
        //127

        CONSORTIA_TRYIN = 129,
        CONSORTIA_CREATE,
        CONSORTIA_DELETE,
        CONSORTIA_USERS_DELETE,
        CONSORTIA_TRYIN_PASS,
        CONSORTIA_TRYIN_DEL,
        CONSORTIA_RICHES_OFFER,
        CONSORTIA_APPLY_STATE,
        CONSORTIA_DUTY_ADD,
        CONSORTIA_DUTY_DELETE,
        CONSORTIA_DUTY_UPDATE,
        CONSORTIA_INVITE,
        //140

        CONSORTIA_INVITE_PASS = 142,
        CONSORTIA_INVITE_DELETE,
        CONSORTIA_ALLY_APPLY_ADD,
        CONSORTIA_ALLY_APPLY_UPDATE,
        CONSORTIA_ALLY_APPLY_DELETE,
        CONSORTIA_ALLY_ADD,
        CONSORTIA_ALLY_DELETE,
        CONSORTIA_DESCRIPTION_UPDATE,
        CONSORTIA_PLACARD_UPDATE,
        CONSORTIA_BANCHAT_UPDATE,
        CONSORTIA_USER_REMARK_UPDATE,
        CONSORTIA_USER_GRADE_UPDATE,
        CONSORTIA_CHAIRMAN_CHAHGE,
        CONSORTIA_CHAT,
        CONSORTIA_STORE_UPGRADE,
        CONSORTIA_SMITH_UPGRADE,
        CONSORTIA_SHOP_UPGRADE,
        CONSORTIA_UPGRADE,
        FRIEND_ADD,
        FRIEND_REMOVE,
        FRIEND_UPDATE,
        FRIEND_LOGIN,
        FRIEND_LOGOUT,
        FRIEND_STATE,
        FRIEND_RESPONSE,
        CHURCH_MOVIE_OVER,
        UPDATE_SHOPLIMIT,
        PLAYER_EXIT_SPA_ROOM,
        CONSORTIA_EQUIP_CONTROL,
        NickName_Card,
		USER_ITEMS_SAVE,
        SPA_ROOM_UPDATE,
        SPA_ROOM_DISPOSE,
        SPA_ROOM_CREATE,
        QUEST_ADD,
        QUEST_REMOVE,
        QUEST_UPDATE,
        QUEST_FINISH,
        QUSET_OBTAIN,
        QUEST_CHECK,
        ITEM_CHANGE_COLOR,
        CARD_USE,
        BUFF_ADD,
        BUFF_UPDATE,
        BUFF_OBTAIN,
        SPA_SCENE_LOGIN = 187,
        USE_CONSORTIA_REWORK_NAME = 188,

        SPA_ROOM_QUICK_LOGIN = 190,
        SPA_CMD,
        AUCTION_ADD,
        AUCTION_UPDATE,
        AUCTION_DELETE,
        AUCTION_REFRESH,
        PLAYER_SPA_ROOM_TIMEOUT,
        SPA_ROOM_LIST,
        SPA_ROOM_ADD_GUEST,
        SPA_ROOM_REMOVE_GUEST,
        CHECK_CODE,
        SPAROOM_SCENE_STATE,
        SPA_ROOM_LOGIN,
        //202

        UPDATE_SHOPNOTICE = 204,

        GAME_PAIRUP_START = 208,
        GAME_PAIRUP_FAILED,
        GAME_PAIRUP_CANCEL,
        GAME_PAIRUP_ROOM_SETUP,
        SPA_ROOM_LOGIN_REMIND,
        //212

        AAS_STATE_GET = 224,//重复
        AAS_INFO_SET = 224,//重复

        AAS_IDNUM_CHECK = 226,
        AAS_CTRL,
        ACHIEVEMENT_INIT,
		ACHIEVEMENT_UPDATE,
		ACHIEVEMENT_FINISH,
		ACHIEVEMENTDATA_INIT,
        //231

		MARRY_SCENE_CHANGE = 233,
		MARRYPROP_GET,
		MARRYINFO_GET,
		MARRYINFO_ADD,
		MARRYINFO_UPDATE,
		MARRYINFO_DELETE,
		MARRYINFO_REFRESH,
		MARRY_SCENE_LOGIN,
		MARRY_ROOM_CREATE,
		MARRY_ROOM_LOGIN,
		PLAYER_ENTER_MARRY_ROOM,
		PLAYER_EXIT_MARRY_ROOM,
        //244

		MARRY_STATUS = 246,
		MARRY_APPLY,
		DIVORCE_APPLY,
		MARRY_CMD,
		MARRY_APPLY_REPLY,
		SCENE_STATE,
		MARRY_ROOM_STATE,
		MARRY_ROOM_INFO_UPDATE,
		MARRY_ROOM_DISPOSE,
		MARRY_ROOM_UPDATE,
        //255



		MANAGER_LOGIN = 255,//重复
        MANAGER_CMD = 254,//重复
        MANAGER_MSG = 253//重复
    }
}
